### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by david-r-edgar** [greg-js/wdn#1] opened 2016-06-20 23:54 UTC
```
david@KidstyPike:~/I/am/some/random/directory/to/warp/to$ wdn add my_first_warp_point
module.js:328
    throw err;
    ^

Error: Cannot find module '/home/david/I/am/some/random/directory/to/warp/lib/warp.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

I assume the problem is on this line in wdn.sh:
`DIR="$(node ${WD}/../lib/warp.js $@)"`

I hard-coded it by way of a hacky fix, but then came up with this:

```
david@KidstyPike:~/I/am/some/random/directory/to/warp/to$ wdn add my_first_warp_point
{ [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/wdn/persist']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/wdn/persist' }
/usr/local/lib/node_modules/wdn/node_modules/node-persist/src/local-storage.js:33
        if (err) throw err;
                 ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/wdn/persist'
    at Error (native)
```

I'm slightly worried by the directory structure indicated by `/usr/local/lib/node_modules/wdn/node_modules/node-persist/src/local-storage.js`. Have the dependencies installed in the correct location...?

(But bear in mind that I'm a node/npm novice, just installed today.)

**Comment by greg-js** [comment] 2016-06-21 00:04
Oh hi David! :)

Thanks for the bug report, I was actually just working on this! The problem is in my tests I had been using `nvm` (node version manager), which installs arbitrary versions of node somewhere in the home dir, thus giving it write permissions for the `persist` dir used in this package. When installed globally however, as you did with `apt-get` or a different package manager, that dir doesn't have write permissions as it goes into `/usr/local/....`.

I'd been thinking about where to store the warp points instead and am leaning towards `~/.config/wdn`. Alternatively I might change some stuff around and use a `.warprc` file instead. Either way, expect a fix pretty soon

We should go get another beer soon btw! ;-)

**Comment by greg-js** [comment] 2016-06-21 02:27
Turned out I only internalized the second half of your message back when I first responded. The permissions issue was fixed half an hour ago by moving the persistence dir, but the first problem you reported was something completely different -- I'd been assuming compatibility between `zsh` and `bash` for the simple code in `./bin/wdn`, but it appears that both identifying the script location and combining regular expressions in a test follows a different syntax in those shells. Never realized it since during my bash tests I was actually still executing `zsh` thanks to my `$SHELL` environment variable not updating automatically ;-)

Anyway, it should be fixed. When you find some time, please update to v2.1.0 using `npm install -g wdn` and check if the problem has been resolved so we can go get that beer.

**Comment by david-r-edgar** [comment] 2016-06-21 09:05
Hi Greg!

Ah, great. Seems to have fixed that problem... But I now hit:

```
david@KidstyPike:~/I/am/some/random/directory/to/warp/to$ wdn add my_first_warp_point
/usr/local/lib/node_modules/wdn/bin/cli.js:31
let options = minimist(process.argv.slice(2), defaults);
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3


david@KidstyPike:~/I/am/some/random/directory/to/warp/to$ nodejs -v
v4.2.6
```

I put in a `'use strict':` in cli.js, and list.js (which reported a similar problem).
Then I get the following:

```
david@KidstyPike:~/I/am/some/random/directory/to/warp/to$ wdn add my_first_warp_point
/usr/local/lib/node_modules/wdn/bin/cli.js:37
if (keywords.includes(firstArg)) {
             ^

TypeError: keywords.includes is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/wdn/bin/cli.js:37:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

If it's relevant, I'm using nodejs v4.2.6 (the default version using plain xubuntu 16.04, I suppose).

**Comment by greg-js** [comment] 2016-06-21 09:55
Now that is strange. This does depend on nodejs >=v6.0, as set in `package.json`. I just did a quick test on an earlier node version and while it produces this warning in the console:

```
npm WARN engine wdn@2.1.0: wanted: {"node":">=6.0"} (current: {"node":"4.4.5","npm":"2.15.5"})
```

It then happily installs the package anyway!

I checked and there is an additional `engineStrict` flag that can be set in `package.json` to, in the words of the official docs, `specify the version of node that your stuff works on`. However, that flag was deprecated in the previous major version of npm, in favor of having users set their own npm config like this: `npm config set engine-strict true` to prevent **themselves** from installing packages that don't match their node/npm version.

To me that seems to completely miss the point though, because there definitely is a use case for preventing users from installing the package on earlier versions, especially considering that Node v4 and v6 both added a ton of ES6-features compared to earlier versions.

I can't imagine there is no other way to do this, so I'll look around for an alternate solution rather than use the deprecated flag. If not, I guess I'll just quickly rewrite it to ES5-compliant code or include a transpiler. Which is silly as the only reason why I required Node v6 is so I could use the fancy new ES6 stuff.

**Comment by greg-js** [comment] 2016-06-21 10:35
I don't think there exists a non-deprecated option for what I was trying to do, so I figured it just wasn't worth it and got rid of all the ES6. It should now be compatible with Node v0.12+

**Comment by david-r-edgar** [comment] 2016-06-21 10:57
woo! Seems to be working now.

That's quite annoying about the ES6, though.

One other comment is that `npm install -g wdn` requires root for me. I'd suggest you add a sudo in the readme. Or maybe it could work fine without -g?
I don't know if it's possible to do anything more to check / catch the permission error? (Currently I get 20 lines of `npm ERR! ...` which doesn't look very nice (though it does correctly identify the problem)).

**Comment by greg-js** [comment] 2016-06-21 11:46
Score!

About the root requirement, it is only required for installing global packages if node is installed via the package manager -- due to the root folder for global packages then being in `/usr/lib` or `usr/local`. People using [nvm](https://github.com/creationix/nvm) won't need it as that folder will be in `.nvm/versions/node/vX`. You're right though, I should probably make that clear in the readme.

It would be possible to install this locally (without the `-g`), but it's not recommended for a command-line tool. One reason is that the user would then have to manually set up an alias or symlink to the script (the current line added in `.bashrc` is particular to this script because it needs `source` to gain the ability to change the working directory in the current process, such a line wouldn't be needed for 99% of global npm packages). Another reason is the fact that the package would then be installed in an arbitrary location: in a `node_modules` subfolder of whatever directory you ran `npm install` in.

Could you paste those `npm ERR!` lines here for me if you're still getting them on a fresh `npm install -g wdn`? Right now I'm not able to produce any errors or warnings, except for a single useless warning on <v0.12.

**Comment by david-r-edgar** [comment] 2016-06-21 14:33
Ah, I see - I don't know anything about nvm (yet), but that makes sense.

This is what I see now:

```
david@KidstyPike:~$ npm install -g wdn
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/wdn
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
/usr/local/lib
└── wdn@2.2.0 

npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "wdn"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib/node_modules/wdn
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/wdn'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/wdn']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/wdn' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/david/npm-debug.log
```

**Comment by greg-js** [comment] 2016-06-21 15:50
Ahh yes, I didn't realize it was this particular npm error you meant. It is outside the scope of this package but to `npm` without `sudo` you will need to [change the global `prefix`](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md). Or you can use a version manager or, somewhat dangerously, simply change the permissions or ownership of [the default global folders](https://docs.npmjs.com/files/folders).

Anyway, looks like this issue has been solved, thanks for reporting it and see you soon :)

**Closed as completed by greg-js** 2016-06-21 15:50 UTC
